// src/errors/errorCodes.js

export const ERROR_CODES = {
    APPLICATION_ERROR: "APPLICATION_ERROR",

    // Request validation errors
    INVALID_JSON: "INVALID_JSON",
    UNSUPPORTED_FIELDS: "UNSUPPORTED_FIELDS",
    MISSING_FIELDS: "MISSING_FIELDS",

    // Entity lookup errors
    USER_NOT_FOUND: "USER_NOT_FOUND",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",

    //Resource validation error codes
    INVALID_RESOURCE_ID: "INVALID_RESOURCE_ID",
    RESOURCE_VALIDATION_FAILED: "RESOURCE_VALIDATION_FAILED",

    //Booking validation error codes
    INVALID_BOOKING_ID: "INVALID_BOOKING_ID",
    BOOKING_VALIDATION_FAILED: "BOOKING_VALIDATION_FAILED",

    //User validation error codes
    INVALID_USER_ID: "INVALID_USER_ID",

    // Booking business-rule errors
    BOOKING_CONFLICT: "BOOKING_CONFLICT",

    // Routing and server errors
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

    // Authentication error codes
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
    FORBIDDEN: "FORBIDDEN",
    AUTH_VALIDATION_FAILED: "AUTH_VALIDATION_FAILED",

    //Signing in error codes
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",

    INVALID_BOOKING_STATUS: "INVALID_BOOKING_STATUS",
    INVALID_BOOKING_STATUS_TRANSITION: "INVALID_BOOKING_STATUS_TRANSITION"

};


