// src/errors/errorCodes.js

export const ERROR_CODES = {
    APPLICATION_ERROR: "APPLICATION_ERROR",

    INVALID_JSON: "INVALID_JSON",
    UNSUPPORTED_FIELDS: "UNSUPPORTED_FIELDS",

    INVALID_RESOURCE_ID: "INVALID_RESOURCE_ID",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    RESOURCE_VALIDATION_FAILED: "RESOURCE_VALIDATION_FAILED",

    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};